### ISSUE TITLE
HR should be able to view all departments

### ISSUE THREAD

**Issue by JoeShep** [elated-egrets/bangazon-internal-site#7]
## Acceptance Criteria

**Given** user wants to view departments
**When** user clicks on the Departments section in the navigation bar
**Then** all current departments should be listed

## Testing Criteria

* Your test suite must verify that the response has a `departments` collection in the context.
* Your test suite must verify that the content of the response has one, or more, of the expected values. For example, if one of the departments in your database in "Sales", then you must verify that is exists in the content.

**Comment by Ryoung27** [comment]
What kind of information should they be able to see?

**Comment by RileyMathews** [comment]
show department names

**Comment by paulzimmclay** [comment]
Sub-steps to done:

- [ ] Write tests
- [ ] Link out to detail view for each department
